deploy:
  build:
    - cd JDC && npm install
    - cd JDC && npm run build
    - cp -r JDC/dist/* htdocs/
    - mkdir -p htdocs/api htdocs/sync htdocs/install
    - cp htdocs/api/* htdocs/api/ 2>/dev/null || true
    - cp htdocs/sync/* htdocs/sync/ 2>/dev/null || true
    - cp htdocs/install/* htdocs/install/ 2>/dev/null || true
    - cp export.xml htdocs/ 2>/dev/null || true
